fixed bug in prepare function and added trend and constant columns
ssoudan/unit-root pull request #7
Opened 2023-10-09 23:25 UTC by ll01

I think this is what is needed, however now some of the matrix are failing to invert in other tests. I know the python version uses sudo invert, but I don't know how that will affect performance.

2023-10-10 00:56 UTC, ll01 commented
#3

2023-10-10 02:39 UTC, ssoudan commented
Thanks and apologies for misguiding you about the column of `1`: 

After a bit of digging, the column of `1` was actually already added in the `ols` code (https://github.com/ssoudan/unit-root/blob/190750e7ecff43779da959170ccf97fad2ed5b96/src/regression.rs#L28). The code without the change is already doing the 'constant no trends' - similar to statsmodels's default. 

Took me some time to figure out why I used `t_stats[1]`, in https://github.com/ssoudan/unit-root/blob/190750e7ecff43779da959170ccf97fad2ed5b96/src/tools/adf.rs#L36 .

The test statistics is the approximate coefficient of the y[t-1] divided by its SE (https://en.wikipedia.org/wiki/Augmented_Dickey–Fuller_test#Testing_procedure).

The column of `1` was added in the first position, so the \hat{y}[t-1] is in the second coefficient. 

Bottom line, if we remove the constant column from the ols() function it is not longer an ols. I think the named should be changed to `regress` or something like that. The method is public but only exposed when the feature 'unstable' is used - and it it intended to be used only by the benchmarks. Then depending on where the y[t-1] is, the right test statistics need to be pulled.

2023-10-10 17:37 UTC, ssoudan requested changes
Looking good! Once the 'println' is removed, I'm thinking of merging this PR and you can create another one to expose the new tests that the changes you introduced allow. Works for you?

2023-10-10 17:37 UTC, ssoudan commented on src/tools/dickeyfuller.rs
> +    println!("t_stats: {}", t_stats);
-println

2023-10-11 00:16 UTC, ssoudan approved these changes

2023-10-11 00:16 UTC, merged

2023-10-11 00:16 UTC, ssoudan commented
Thanks!